### ISSUE TITLE
PA Digitale - Chiarimenti su API di Conferimento dati al SIUSS

### ISSUE THREAD

**Issue by SimoneCiapi** [INPS-it/WaaS.Comuni#10]
Pa Digitale sta predisponendo le API di alimentazione del SSIUS dal nostro sistema URBI.

Analizzando la sezione relativa alla Get/flussi ci siamo posti alcuni quesiti.

Innanzitutto abbiamo interpretato che il parametro 'since' sia la data erogazione dell'ultima prestazione trasmessa; se ciò è corretto allora vi sottoponiamo i seguenti punti:

1. in caso di prima chiamata (since=-1) quali prestazioni l'ente dovrebbe restituire? Molti nostri clienti trasmettevano già con URBI i flussi di prestazioni

2. una volta a regime, se l'ultima chiamata è stata fatta con since='data X', e se in urbi sono state create prestazioni con data erogazione pregressa, ovvero minore di 'data X', queste non verrebbero restituite: si potranno continuare a trasmettere con la vecchia modalità?

3.l'operatore abilitato continuerà a generare in URBI i flussi che resteranno in attesa della chiamata Get/flussi?

4.se la chiamata viene fatta con la limit=10 e since=dataX, URBI estae tutte le prestazioni erogate dopo la dataX e ne mette in risposta le prime 10 ;
se il beneficiario ROSSI MIRKO ha una prestazione in data 1 e un'altra in data 2 noi estraevamo un xml in cui ,all'interno del tag beneficiario, era presente sia la prestazione 1 che la prestazione2, come di seguito riportato: la struttura che segue può considerarsi ancora valida?

`<Beneficiario CodiceFiscale="RSSMRK66C14H501U">  
<Anagrafica Nome="MIRKO" CodiceCittadinanza="380" Genere="1" LuogoNascita="H501" AnnoNascita="1966" Cognome="ROSSI"/>
<Indirizzo CodiceNazione="380" CodiceComune="068001" CodiceRegione="13"/>
<PrestazioniSociali AreaUtenza="3" PresaCarico="1" ImportoQuotaEnte="459.83" ImportoMensile="459.83" PeriodoErogazione="1" DataFinePrestazione="2022-10-28" DataInizioPrestazione="2022-10-28" DataEvento="2022-10-14" ProtocolloDomanda="2022.13340" DenominazionePrestazione="Contributi economici a integrazione del reddito familiare" CodicePrestazione="A1.04" CaratterePrestazione="1" PresenzaProvaMezzi="2"> </PrestazioniSociali>
<PrestazioniSociali AreaUtenza="3" PresaCarico="1" ImportoQuotaEnte="459.83" ImportoMensile="459.83" PeriodoErogazione="1" DataFinePrestazione="2022-11-28" DataInizioPrestazione="2022-11-28" DataEvento="2022-10-14" ProtocolloDomanda="2022.13340" DenominazionePrestazione="Contributi economici a integrazione del reddito familiare" CodicePrestazione="A1.04" CaratterePrestazione="1" PresenzaProvaMezzi="2"> </PrestazioniSociali>
</Beneficiario>`

dunque si continua a trasmettere sia la prestazione1 che la prestazione 2 ?

5. sempre relativamente alla chiamata  gest flussi, nell'esempio si legge:
GET /flussi?max_entries=10&since=2017-07-21T17:32:28Z
quindi all'ente viene chiesto di rispondere con 10 prestazioni che abbiamo data erogazione successiva al 2017-07-21T17:32:28Z
nell'esempio di risposta però (di seguito decodificato) sono presenti delle date non coerenti con il since...
DataInizioPrestazione="2015-08-13" (in URBI si prendeva la data erogazione della prestazione)
DataEvento="2016-10-13" (in URBI si prendeva la data del protocollo principale)
DataFinePrestazione="2016-08-13"(in URBI si prendeva la data erogazione della prestazione)

`<Flusso xmlns="http://inps.it/Casellario" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">  
<IdentificazioneFlusso Nome="H501.PS.INPS.20160423.115235">  
<Ente Denominazione="Comune di Roma" Codice="H501" CFOperatore="XXXXXX80P20B501B" Indirizzo="H501"/>  
</IdentificazioneFlusso>  
<Beneficiario CodiceFiscale="RSSMRK66C14H501U">  
<Anagrafica AnnoNascita="1966" Genere="1" CodiceCittadinanza="380" Nome="MIRKO" CodiceSecondaCittadinanza="380" LuogoNascita="H501" Cognome="ROSSI"/>  
<Indirizzo CodiceComune="068001" CodiceNazione="380" CodiceRegione="01"/>  
<PrestazioniSociali CaratterePrestazione="1" AreaUtenza="2" ImportoQuotaUtente="0.0" ImportoQuotaRichiesta="0.0" TipoOperazione="I" DataInizioPrestazione="2015-08-13" CodicePrestazione="A2.16" DenominazionePrestazione="Interventi di supporto per reperimento alloggi" ProtocolloDomanda="Protocollo fittizio" DataEvento="2016-10-13" ImportoMensile="200.0" ImportoQuotaSSN="0.0" PeriodoErogazione="1" ImportoSogliaISEE="0.0" PresaCarico="1" DataFinePrestazione="2016-08-13" ImportoQuotaEnte="0.0" PresenzaProvaMezzi="2" OreServizioMensile="2">  
<SINA NecessitaCureSanitarie="1" FonteDerivazioneInvalidita="1" AreaReddituale="1" StrumentoValutazione="1" FonteDerivazioneValutazione="1" AreaSupporto="1" Mobilita="1" DisturbiComportamentali="1" AttivitaVitaQuotidiana="1">  
<NecessitaInterventiSociali>  
<CodicePrestazione>A1.01</CodicePrestazione>  
<CodicePrestazione>A1.02</CodicePrestazione>  
</NecessitaInterventiSociali>  
<InvaliditaCivile>  
<InvCiv>1</InvCiv>  
<InvCiv>2</InvCiv>  
</InvaliditaCivile>  
</SINA>  
</PrestazioniSociali>  
</Beneficiario>  
</Flusso>`

Ci piacerebbe organizzare una sessione di condivisione ai primi di Settembre: sareste disponibili?
Ringraziamo in anticipo.

Teresa Pepe
Simone Ciapi

**Comment by andreacigliano** [comment]
A seguire le risposte alle issues sottomesse:

**Domanda 1.a)**
Pa Digitale sta predisponendo le API di alimentazione del SSIUS dal nostro sistema URBI.
Analizzando la sezione relativa alla Get/flussi ci siamo posti alcuni quesiti.
Innanzitutto abbiamo interpretato che il parametro 'since' sia la data erogazione dell'ultima prestazione trasmessa; 
**Risposta 1.a)**
Il parametro since non fa riferimento alla data di erogazione dell'ultima prestazione trasmessa. Si tratta invece di un riferimento alla data del flusso che assume valore esclusivamente internamente al dominio del Welfare Provider ed esclusivamente finalizzato a condividere tra INPS e Welfare Provider l'avanzamento dell'acquisizione da parte di INPS dei flussi prodotti dal Provider.
INPS si limita quindi a memorizzare il timestamp dell'ultimo flusso acquisito (parametro ts_flusso della risposta dell'Ente), che sarà poi utilizzato come valore del parametro since nella successiva richiesta.

**Domanda 1.b)**
se ciò è corretto allora vi sottoponiamo i seguenti punti:
•	in caso di prima chiamata (since=-1) quali prestazioni l'ente dovrebbe restituire? Molti nostri clienti trasmettevano già con URBI i flussi di prestazioni
**Risposta 1.b)**
I diversi sistemi di acquisizione di INPS sono tra loro integrati, l'Ente può quindi limitarsi a trasferire le prestazioni non ancora trasmesse su altri canali.

**Domanda 1.c)**
una volta a regime, se l'ultima chiamata è stata fatta con since='data X', e se in urbi sono state create prestazioni con data erogazione pregressa, ovvero minore di 'data X', queste non verrebbero restituite: si potranno continuare a trasmettere con la vecchia modalità?
**Risposta 1.c)**
Saranno acquisite regolarmente, l'importante è che il timestamp nel parametro 'ts_flusso', nel JSON della risposta dell'Ente, sia successivo al parametro 'since', indipendentemente dalla data erogazione delle prestazioni inserite nel flusso.

**Domanda 1.d)**
3.l'operatore abilitato continuerà a generare in URBI i flussi che resteranno in attesa della chiamata Get/flussi?
**Risposta 1.d)**
La domanda non è chiara, potete precisare meglio?

**Domanda 1.e)**
4.se la chiamata viene fatta con la limit=10 e since=dataX, URBI estae tutte le prestazioni erogate dopo la dataX e ne mette in risposta le prime 10 ;
se il beneficiario ROSSI MIRKO ha una prestazione in data 1 e un'altra in data 2 noi estraevamo un xml in cui ,all'interno del tag beneficiario, era presente sia la prestazione 1 che la prestazione2, come di seguito riportato: la struttura che segue può considerarsi ancora valida?
<Beneficiario CodiceFiscale="RSSMRK66C14H501U"> <Anagrafica Nome="MIRKO" CodiceCittadinanza="380" Genere="1" LuogoNascita="H501" AnnoNascita="1966" Cognome="ROSSI"/> <Indirizzo CodiceNazione="380" CodiceComune="068001" CodiceRegione="13"/> <PrestazioniSociali AreaUtenza="3" PresaCarico="1" ImportoQuotaEnte="459.83" ImportoMensile="459.83" PeriodoErogazione="1" DataFinePrestazione="2022-10-28" DataInizioPrestazione="2022-10-28" DataEvento="2022-10-14" ProtocolloDomanda="2022.13340" DenominazionePrestazione="Contributi economici a integrazione del reddito familiare" CodicePrestazione="A1.04" CaratterePrestazione="1" PresenzaProvaMezzi="2"> </PrestazioniSociali> <PrestazioniSociali AreaUtenza="3" PresaCarico="1" ImportoQuotaEnte="459.83" ImportoMensile="459.83" PeriodoErogazione="1" DataFinePrestazione="2022-11-28" DataInizioPrestazione="2022-11-28" DataEvento="2022-10-14" ProtocolloDomanda="2022.13340" DenominazionePrestazione="Contributi economici a integrazione del reddito familiare" CodicePrestazione="A1.04" CaratterePrestazione="1" PresenzaProvaMezzi="2"> </PrestazioniSociali> </Beneficiario>
dunque si continua a trasmettere sia la prestazione1 che la prestazione 2 ?
**Risposta 1.e)**
Come indicato in premessa, il contenuto dei flussi può essere liberamente organizzato dall'Ente, fermo restando che abbiano un timestamp incrementale che permetta a INPS di acquisire per ogni nuova rihiesta dati non ancora acquisiti.

**Domanda 1.f)**
5.	sempre relativamente alla chiamata gest flussi, nell'esempio si legge:
GET /flussi?max_entries=10&since=2017-07-21T17:32:28Z
quindi all'ente viene chiesto di rispondere con 10 prestazioni che abbiamo data erogazione successiva al 2017-07-21T17:32:28Z
nell'esempio di risposta però (di seguito decodificato) sono presenti delle date non coerenti con il since...
DataInizioPrestazione="2015-08-13" (in URBI si prendeva la data erogazione della prestazione)
DataEvento="2016-10-13" (in URBI si prendeva la data del protocollo principale)
DataFinePrestazione="2016-08-13"(in URBI si prendeva la data erogazione della prestazione)
<Flusso xmlns=http://inps.it/Casellario xmlns:xsi=http://www.w3.org/2001/XMLSchema-instance> <IdentificazioneFlusso Nome="H501.PS.INPS.20160423.115235"> <Ente Denominazione="Comune di Roma" Codice="H501" CFOperatore="XXXXXX80P20B501B" Indirizzo="H501"/> </IdentificazioneFlusso> <Beneficiario CodiceFiscale="RSSMRK66C14H501U"> <Anagrafica AnnoNascita="1966" Genere="1" CodiceCittadinanza="380" Nome="MIRKO" CodiceSecondaCittadinanza="380" LuogoNascita="H501" Cognome="ROSSI"/> <Indirizzo CodiceComune="068001" CodiceNazione="380" CodiceRegione="01"/> <PrestazioniSociali CaratterePrestazione="1" AreaUtenza="2" ImportoQuotaUtente="0.0" ImportoQuotaRichiesta="0.0" TipoOperazione="I" DataInizioPrestazione="2015-08-13" CodicePrestazione="A2.16" DenominazionePrestazione="Interventi di supporto per reperimento alloggi" ProtocolloDomanda="Protocollo fittizio" DataEvento="2016-10-13" ImportoMensile="200.0" ImportoQuotaSSN="0.0" PeriodoErogazione="1" ImportoSogliaISEE="0.0" PresaCarico="1" DataFinePrestazione="2016-08-13" ImportoQuotaEnte="0.0" PresenzaProvaMezzi="2" OreServizioMensile="2"> <SINA NecessitaCureSanitarie="1" FonteDerivazioneInvalidita="1" AreaReddituale="1" StrumentoValutazione="1" FonteDerivazioneValutazione="1" AreaSupporto="1" Mobilita="1" DisturbiComportamentali="1" AttivitaVitaQuotidiana="1"> <NecessitaInterventiSociali> <CodicePrestazione>A1.01</CodicePrestazione> <CodicePrestazione>A1.02</CodicePrestazione> </NecessitaInterventiSociali> <InvaliditaCivile> <InvCiv>1</InvCiv> <InvCiv>2</InvCiv> </InvaliditaCivile> </SINA> </PrestazioniSociali> </Beneficiario> </Flusso>
**Risposta 1.f)**
Fermo restando che i dati degli esempi non sono dati significativi, per i motivi già riportati, il prametro since è relativo al timestamp che identifica il flusso e non le singole prestazioni contenute nel flusso.

**Comment by SimoneCiapi** [comment]
Buongiorno, grazie per le risposte.
La domanda 1.d era legata ad un nostro dubbio relativo alla modalità di invio dei flussi, ma la Vostra risposta
relativa all'utilizzo del parametro since ha sciolto il dubbio stesso.

Cordiali saluti,
Teresa Pepe
Simone Ciapi

**Comment by MBossiniB** [comment]
Buongiorno,

mi riaggancio a questa issue perchè non mi è chiara la risposta alla domanda 1.e).

Nel file PS_PSA_SINA201812.xsd è riportata la seguente dicitura: "tramite cooperazione applicativa è consentito l'invio di una sola prestaizone per ogni XML, nel caso di invio tramite upload di file XML/CSV da applicazione web si possono inviare più prestazioni".

Quindi mi verrebbe da dire che tramite API non sia possibile inserire più di una prestazione per XML e quindi per ogni beneficiario. Vi chiederei una delucidazione perchè potrei aver male interpretato.

Grazie
Cordiali saluti
Martina Bossini
